const mobs={
    "cape":{
        "cape":{
            "origin":[-5,8,-3],
            "size":[10,16,1],
            "uv":[0,0]
        }
    },
    "steve":{
        "body":{
            "name":"body",
            "origin":[-4,12,-2],
            "size":[8,12,4],
            "uv":[16,16]
        },
        "head":{
            "name":"head",
            "origin":[-4,24,-4],
            "size":[8,8,8],
            "uv":[0,0]
        },
        "rightLeg":{
            "name":"rightLeg",
            "origin":[-3.9,0,-2],
            "size":[4,12,4],
            "uv":[0,16]
        },
        "leftLeg":{
            "name":"leftLeg",
            "origin":[-0.1,0,-2],
            "size":[4,12,4],
            "uv":[16,48]
        },
        "hat":{
            "name":"hat",
            "origin":[-4,24,-4],
            "size":[8,8,8],
            "uv":[32,0],
            "inflate":0.5
        },
        "leftArm":{
            "name":"leftArm",
            "origin":[4,12,-2],
            "size":[4,12,4],
            "uv":[32,48]
        },
        "rightArm":{
            "name":"rightArm",
            "origin":[-8,12,-2],
            "size":[4,12,4],
            "uv":[40,16]
        },
        "leftSleeve":{
            "name":"leftSleeve",
            "origin":[4,12,-2],
            "size":[4,12,4],
            "uv":[48,48],
            "inflate":0.25
        },
        "rightSleeve":{
            "name":"rightSleeve",
            "origin":[-8,12,-2],
            "size":[4,12,4],
            "uv":[40,32],
            "inflate":0.25
        },
        "leftPants":{
            "name":"leftPants",
            "origin":[-0.1,0,-2],
            "size":[4,12,4],
            "uv":[0,48],
            "inflate":0.25
        },
        "rightPants":{
            "name":"rightPants",
            "origin":[-3.9,0,-2],
            "size":[4,12,4],
            "uv":[0,32],
            "inflate":0.25
        },
        "jacket":{
            "name":"jacket",
            "origin":[-4,12,-2],
            "size":[8,12,4],
            "uv":[16,32],
            "inflate":0.25
        }
    },
    "alex":{
        "body":{
            "name":"body",
            "origin":[-4,12,-2],
            "size":[8,12,4],
            "uv":[16,16]
        },
        "head":{
            "name":"head",
            "origin":[-4,24,-4],
            "size":[8,8,8],
            "uv":[0,0]
        },
        "rightLeg":{
            "name":"rightLeg",
            "origin":[-3.9,0,-2],
            "size":[4,12,4],
            "uv":[0,16]
        },
        "leftLeg":{
            "name":"leftLeg",
            "origin":[-0.1,0,-2],
            "size":[4,12,4],
            "uv":[16,48]
        },
        "hat":{
            "name":"hat",
            "origin":[-4,24,-4],
            "size":[8,8,8],
            "uv":[32,0],
            "inflate":0.5
        },
        "leftArm":{
            "name":"leftArm",
            "origin":[4,11.5,-2],
            "size":[3,12,4],
            "uv":[32,48]
        },
        "rightArm":{
            "name":"rightArm",
            "origin":[-7,11.5,-2],
            "size":[3,12,4],
            "uv":[40,16]
        },
        "leftSleeve":{
            "name":"leftSleeve",
            "origin":[4,11.5,-2],
            "size":[3,12,4],
            "uv":[48,48],
            "inflate":0.25
        },
        "rightSleeve":{
            "name":"rightSleeve",
            "origin":[-7,11.5,-2],
            "size":[3,12,4],
            "uv":[40,32],
            "inflate":0.25
        },
        "leftPants":{
            "name":"leftPants",
            "origin":[-0.1,0,-2],
            "size":[4,12,4],
            "uv":[0,48],
            "inflate":0.25
        },
        "rightPants":{
            "name":"rightPants",
            "origin":[-3.9,0,-2],
            "size":[4,12,4],
            "uv":[0,32],
            "inflate":0.25
        },
        "jacket":{
            "name":"jacket",
            "origin":[-4,12,-2],
            "size":[8,12,4],
            "uv":[16,32],
            "inflate":0.25
        }
    }
}